export const posts = [
  {
    index: 1,
    img: "https://picsum.photos/800/600?1",
    title: "Exploring the Future of AI Design Systems",
    subtitle: "How generative UI is reshaping product workflows",
    postId: "123456",
    type: "post-1",
    content: "hi im here",
  },
  {
    index: 2,
    img: "https://picsum.photos/800/600?2",
    title: "Scaling Serverless Architectures",
    subtitle: "Lessons from high-volume cloud pipelines",
    postId: "12343789456123",
    type: "post-1",
    content: "hi im here",
  },
  {
    index: 3,
    img: "https://picsum.photos/800/600?3",
    title: "Building Reactive Data Platforms",
    subtitle: "Streaming, batching and orchestration",
    postId: "1593659",
    type: "post-1",
    content: "hi im here",
  },
  {
    index: 4,
    img: "https://picsum.photos/800/600?4",
    title: "Modern Frontend Observability",
    subtitle: "Tracing UX performance in real time",
    postId: "987564",
    type: "post-1",
    content: "hi im here",
  },
  {
    index: 5,
    img: "https://picsum.photos/800/600?5",
    title: "Design Tokens at Scale",
    subtitle: "Unifying brand across ecosystems",
    postId: "257412",
    type: "post-2",
    content: "hi im here",
  },
  {
    index: 6,
    img: "https://picsum.photos/800/600?6",
    title: "Event-Driven Commerce Platforms",
    subtitle: "Async workflows for global stores",
    postId: "369147",
    type: "post-2",
    content: "hi im here",
  },
  {
    index: 7,
    img: "https://picsum.photos/800/600?7",
    title: "Edge Functions in Production",
    subtitle: "Latency wins and tradeoffs",
    postId: "456123",
    type: "post-2",
    content: "hi im here",
  },
  {
    index: 8,
    img: "https://picsum.photos/800/600?8",
    title: "Composable Content Systems",
    subtitle: "Headless CMS done right",
    postId: "758412",
    type: "post-3",
    content: "hi im here programming",
  },
  {
    index: 9,
    img: "https://picsum.photos/800/600?9",
    title: "Realtime Collaboration Engines",
    subtitle: "CRDTs and multiplayer editing",
    postId: "325698",
    type: "post-3",
    content: "hi im here programming",
  },
  {
    index: 10,
    img: "https://picsum.photos/800/600?10",
    title: "Search UX that Converts",
    subtitle: "Patterns from top marketplaces",
    postId: "856932",
    type: "post-3",
    content: "hi im here programming",
  },
];
