sonar.host.url=https://sonarcloud.io
sonar.organization=sparknco
sonar.projectKey=marketing-site
sonar.projectName=Marketing site

sonar.sources=src
sonar.sourceEncoding=UTF-8

sonar.typescript.tsconfigPath=tsconfig.json

sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**,**/.vercel/**,**/.cache/**,**/coverage/**,**/*.min.js
