export const HeroSectionSquaresConfig = [
  {
    left: 0,
    top: 0,
    width: 14,
    height: 26,
    color: "#F7F4F0",
    colorDelay: 20,
    duration: 15,
    zIndex: 0,
  },
  {
    left: 14,
    bottom: 0,
    width: 10,
    height: 15,
    colorDelay: 1,
    duration: 1,
    zIndex: 1,
  },
  {
    left: 14,
    bottom: 11,
    width: 2,
    height: 2,
    color: "#f78035",
    colorDelay: 1,
    duration: 1,
    zIndex: 1,
  },
  {
    left: 16,
    bottom: 11,
    width: 4,
    height: 2,
    color: "#faf6ef",
    zIndex: 2,
  },
  {
    left: 16,
    bottom: 11,
    width: 1,
    height: 1,
    color: "#111111",
    zIndex: 3,
  },
  {
    left: 12,
    bottom: 6,
    width: 2,
    height: 2,
    color: "#111111",
    zIndex: 5,
  },
  {
    left: 16,
    bottom: 10,
    width: 1,
    height: 1,
    color: "#B65F28",
    color2: "#111111",
    zIndex: 3,
    colorDelay: 5,
    duration: 1,
  },
  {
    left: 14,
    bottom: 6,
    width: 2,
    height: 2,
    color: "#F7F4F0",
    zIndex: 1,
  },
  {
    // ESTE
    left: 13,
    bottom: 8,
    width: 1,
    height: 1,
    color: "#f78035",
    zIndex: 0,
  },
  {
    left: 17,
    bottom: 8,
    width: 1,
    height: 1,
    color: "#f78035",
    zIndex: 2,
  },
  {
    left: 10,
    bottom: 5,
    width: 1,
    height: 1,
    color: "#f78035",
    zIndex: 4,
  },
  {
    left: 13,
    bottom: 5,
    width: 1,
    height: 1,
    color: "#f78035",
    zIndex: 4,
  },
  {
    left: 21,
    bottom: 11,
    width: 1,
    height: 1,
    color: "#f8f8f8",
    zIndex: 4,
  },
  {
    left: 10,
    bottom: 2,
    width: 4,
    height: 4,
    color: "#111111",
    zIndex: 1,
  },
  {
    left: 2,
    bottom: 0,
    width: 12,
    height: 2,
    color: "#111111",
    zIndex: 1,
  },
  {
    left: 2,
    bottom: 1,
    width: 1,
    height: 1,
    color: "#f78035",
    zIndex: 4,
  },
  {
    left: 4,
    bottom: 0,
    width: 1,
    height: 1,
    color: "#B65F28",
    zIndex: 4,
  },
  {
    left: 8,
    bottom: 2,
    width: 1,
    height: 1,
    color: "#f78035",
    zIndex: 4,
  },
];

export const FastTrackSquaresConfig = [
  {
    top: 0,
    left: 0,
    width: 40,
    height: 19,
    color: "#F7F4F0",
    colorDelay: 20,
    duration: 15,
    zIndex: 0,
  },
  {
    top: 0,
    left: 0,
    width: 23,
    height: 1,
    color: "#111111",
    colorDelay: 20,
    duration: 15,
    zIndex: 0,
  },
  {
    top: 1,
    left: 0,
    width: 23,
    height: 1,
    color: "#111111",
    colorDelay: 20,
    duration: 15,
    zIndex: 0,
  },
  {
    top: 2,
    left: 0,
    width: 13,
    height: 1,
    color: "#111111",
    colorDelay: 20,
    duration: 15,
    zIndex: 0,
  },
  {
    top: 2,
    left: 15,
    width: 2,
    height: 2,
    color: "#f78035",
    colorDelay: 20,
    duration: 15,
    zIndex: 0,
  },
  {
    top: 2,
    left: 17,
    width: 4,
    height: 1,
    color: "#111111",
    colorDelay: 20,
    duration: 15,
    zIndex: 0,
  },
  {
    top: 2,
    left: 20,
    width: 1,
    height: 1,
    color: "#f78035",
    colorDelay: 20,
    duration: 15,
    zIndex: 0,
  },
  {
    top: 3,
    left: 0,
    width: 4,
    height: 4,
    color: "#111111",
    colorDelay: 20,
    duration: 15,
    zIndex: 1,
  },
  {
    top: 3,
    left: 4,
    width: 2,
    height: 2,
    color: "#111111",
    colorDelay: 20,
    duration: 15,
    zIndex: 1,
  },
  {
    top: 3,
    left: 6,
    width: 4,
    height: 1,
    color: "#111111",
    colorDelay: 20,
    duration: 15,
    zIndex: 1,
  },
  {
    top: 4,
    left: 7,
    width: 2,
    height: 1,
    color: "#111111",
    colorDelay: 20,
    duration: 15,
    zIndex: 1,
  },
  {
    top: 3,
    left: 4,
    width: 1,
    height: 1,
    color: "#f78035",
    colorDelay: 20,
    duration: 15,
    zIndex: 3,
  },
  {
    top: 3,
    left: 10,
    width: 1,
    height: 1,
    color: "#f78035",
    colorDelay: 20,
    duration: 15,
    zIndex: 3,
  },
  {
    top: 4,
    left: 3,
    width: 1,
    height: 1,
    color: "#f78035",
    colorDelay: 20,
    duration: 15,
    zIndex: 3,
  },
  {
    top: 6,
    left: 0,
    width: 1,
    height: 1,
    color: "#f78035",
    colorDelay: 20,
    duration: 15,
    zIndex: 2,
  },
  {
    top: 5,
    left: 4,
    width: 1,
    height: 1,
    color: "#f78035",
    colorDelay: 20,
    duration: 15,
    zIndex: 2,
  },
  {
    top: 6,
    left: 2,
    width: 2,
    height: 2,
    color: "#f78035",
    colorDelay: 20,
    duration: 15,
    zIndex: 2,
  },
  {
    top: 7,
    left: 0,
    width: 1,
    height: 1,
    color: "#111111",
    colorDelay: 20,
    duration: 15,
    zIndex: 2,
  },
  {
    top: 0,
    left: 23,
    width: 4,
    height: 2,
    color: "#111111",
    colorDelay: 20,
    duration: 15,
    zIndex: 1,
  },
  {
    top: 0,
    left: 27,
    width: 2,
    height: 2,
    color: "#111111",
    colorDelay: 20,
    duration: 15,
    zIndex: 1,
  },
  {
    top: 0,
    left: 29,
    width: 4,
    height: 1,
    color: "#111111",
    colorDelay: 20,
    duration: 15,
    zIndex: 1,
  },
  {
    top: 1,
    left: 30,
    width: 2,
    height: 1,
    color: "#111111",
    colorDelay: 20,
    duration: 15,
    zIndex: 1,
  },
  {
    top: 1,
    left: 27,
    width: 1,
    height: 1,
    color: "#f78035",
    colorDelay: 20,
    duration: 15,
    zIndex: 3,
  },
  {
    top: 1,
    left: 32,
    width: 1,
    height: 1,
    color: "#f78035",
    colorDelay: 20,
    duration: 15,
    zIndex: 3,
  },
  {
    top: 2,
    left: 24,
    width: 1,
    height: 1,
    color: "#f78035",
    colorDelay: 20,
    duration: 15,
    zIndex: 2,
  },
  {
    top: 3,
    left: 24,
    width: 1,
    height: 1,
    color: "#111111",
    colorDelay: 20,
    duration: 15,
    zIndex: 2,
  },
  {
    top: 2,
    left: 28,
    width: 1,
    height: 1,
    color: "#f78035",
    colorDelay: 20,
    duration: 15,
    zIndex: 4,
  },
  {
    top: 2,
    left: 25,
    width: 1,
    height: 1,
    color: "#111111",
    colorDelay: 20,
    duration: 15,
    zIndex: 2,
  },
  {
    top: 2,
    left: 27,
    width: 1,
    height: 1,
    color: "#111111",
    colorDelay: 20,
    duration: 15,
    zIndex: 2,
  },
  {
    top: 2,
    left: 26,
    width: 2,
    height: 2,
    color: "#B65F28",
    colorDelay: 20,
    duration: 15,
    zIndex: 2,
  },

  /* Bottom Frame (RIGHT ALIGNED) */

  {
    top: 18,
    right: 7,
    width: 14,
    height: 1,
    color: "#111111",
    colorDelay: 20,
    duration: 15,
    zIndex: 0,
  },
  {
    top: 15,
    right: 0,
    width: 8,
    height: 4,
    color: "#111111",
    colorDelay: 20,
    duration: 15,
    zIndex: 0,
  },
  {
    top: 16,
    right: 8,
    width: 2,
    height: 2,
    color: "#111111",
    colorDelay: 20,
    duration: 15,
    zIndex: 0,
  },
  {
    top: 17,
    right: 10,
    width: 7,
    height: 1,
    color: "#111111",
    colorDelay: 20,
    duration: 15,
    zIndex: 0,
  },
  {
    top: 15,
    right: 17,
    width: 1,
    height: 1,
    color: "#F7F4F0",
    colorDelay: 20,
    duration: 15,
    zIndex: 5,
  },
  {
    top: 15,
    right: 19,
    width: 2,
    height: 3,
    color: "#111111",
    colorDelay: 20,
    duration: 15,
    zIndex: 5,
  },
  {
    top: 14,
    right: 18,
    width: 1,
    height: 1,
    color: "#F7F4F0",
    colorDelay: 20,
    duration: 15,
    zIndex: 5,
  },
  {
    top: 14,
    right: 15,
    width: 4,
    height: 3,
    color: "#111111",
    colorDelay: 20,
    duration: 15,
    zIndex: 0,
  },
  {
    top: 15,
    right: 12,
    width: 3,
    height: 3,
    color: "#111111",
    colorDelay: 20,
    duration: 15,
    zIndex: 3,
  },
  {
    top: 17,
    right: 13,
    width: 2,
    height: 1,
    color: "#F7F4F0",
    colorDelay: 20,
    duration: 15,
    zIndex: 1,
  },
  {
    top: 17,
    right: 17,
    width: 1,
    height: 1,
    color: "#f78035",
    colorDelay: 20,
    duration: 15,
    zIndex: 2,
  },
  {
    top: 15,
    right: 9,
    width: 1,
    height: 1,
    color: "#f78035",
    colorDelay: 20,
    duration: 15,
    zIndex: 3,
  },
  {
    top: 16,
    right: 8,
    width: 1,
    height: 1,
    color: "#F7F4F0",
    colorDelay: 20,
    duration: 15,
    zIndex: 3,
  },
  {
    top: 15,
    right: 8,
    width: 1,
    height: 1,
    color: "#111111",
    colorDelay: 20,
    duration: 15,
    zIndex: 3,
  },
  {
    top: 14,
    right: 0,
    width: 8,
    height: 1,
    color: "#111111",
    colorDelay: 20,
    duration: 15,
    zIndex: 1,
  },
  {
    top: 12,
    right: 0,
    width: 4,
    height: 2,
    color: "#111111",
    colorDelay: 20,
    duration: 15,
    zIndex: 1,
  },

  {
    top: 11,
    right: 1,
    width: 1,
    height: 1,
    color: "#f78035",
    colorDelay: 20,
    duration: 15,
    zIndex: 1,
  },
  {
    top: 12,
    right: 3,
    width: 1,
    height: 1,
    color: "#F7F4F0",
    colorDelay: 20,
    duration: 15,
    zIndex: 6,
  },
  {
    top: 12,
    right: 4,
    width: 2,
    height: 2,
    color: "#f78035",
    colorDelay: 20,
    duration: 15,
    zIndex: 2,
  },
  {
    top: 13,
    right: 2,
    width: 1,
    height: 1,
    color: "#F7F4F0",
    colorDelay: 20,
    duration: 15,
    zIndex: 2,
  },
  {
    top: 13,
    right: 6,
    width: 1,
    height: 1,
    color: "#B65F28",
    colorDelay: 20,
    duration: 15,
    zIndex: 1,
  },
  {
    top: 14,
    right: 7,
    width: 1,
    height: 1,
    color: "#B65F28",
    colorDelay: 20,
    duration: 15,
    zIndex: 3,
  },
  {
    top: 17,
    right: 20,
    width: 8,
    height: 2,
    color: "#111111",
    colorDelay: 20,
    duration: 15,
    zIndex: 0,
  },
  {
    top: 18,
    right: 28,
    width: 2,
    height: 1,
    color: "#111111",
    colorDelay: 20,
    duration: 15,
    zIndex: 0,
  },
  {
    top: 19,
    right: 33,
    width: 2,
    height: 1,
    color: "#F7F4F0",
    colorDelay: 20,
    duration: 15,
    zIndex: 1,
  },
  {
    top: 19,
    right: 38,
    width: 1,
    height: 1,
    color: "#f78035",
    colorDelay: 20,
    duration: 15,
    zIndex: 2,
  },
  {
    top: 17,
    right: 29,
    width: 1,
    height: 1,
    color: "#f78035",
    colorDelay: 20,
    duration: 15,
    zIndex: 3,
  },
  {
    top: 18,
    right: 28,
    width: 1,
    height: 1,
    color: "#F7F4F0",
    colorDelay: 20,
    duration: 15,
    zIndex: 3,
  },
  {
    top: 17,
    right: 28,
    width: 1,
    height: 1,
    color: "#111111",
    colorDelay: 20,
    duration: 15,
    zIndex: 3,
  },
  {
    top: 16,
    right: 20,
    width: 8,
    height: 1,
    color: "#111111",
    colorDelay: 20,
    duration: 15,
    zIndex: 1,
  },
  {
    top: 14,
    // right 20,
    right: 22,
    width: 4,
    height: 2,
    color: "#111111",
    colorDelay: 20,
    duration: 15,
    zIndex: 1,
  },
  {
    top: 15,
    right: 20,
    width: 1,
    height: 1,
    color: "#111111",
    colorDelay: 20,
    duration: 15,
    zIndex: 3,
  },

  {
    top: 14,
    right: 21,
    width: 1,
    height: 1,
    color: "white",
    colorDelay: 20,
    duration: 15,
    zIndex: 3,
  },

  {
    top: 14,
    right: 23,
    width: 1,
    height: 1,
    color: "#F7F4F0",
    colorDelay: 20,
    duration: 15,
    zIndex: 6,
  },
  {
    top: 14,
    right: 20,
    //    right 24,
    width: 2,
    height: 2,
    color: "#f78035", // f78035
    colorDelay: 20,
    duration: 15,
    zIndex: 2,
  },
  {
    top: 15,
    right: 22,
    width: 1,
    height: 1,
    color: "#F7F4F0",
    colorDelay: 20,
    duration: 15,
    zIndex: 2,
  },
  {
    top: 15,
    right: 26,
    width: 1,
    height: 1,
    color: "#B65F28",
    colorDelay: 20,
    duration: 15,
    zIndex: 1,
  },
  {
    top: 16,
    right: 27,
    width: 1,
    height: 1,
    color: "#B65F28",
    colorDelay: 20,
    duration: 15,
    zIndex: 3,
  },
  {
    top: 17,
    right: 31,
    width: 2,
    height: 1,
    color: "#111111",
    colorDelay: 20,
    duration: 15,
    zIndex: 5,
  },
  {
    top: 18,
    right: 30,
    width: 7,
    height: 1,
    color: "#111111",
    colorDelay: 20,
    duration: 15,
    zIndex: 5,
  },
  {
    top: 17,
    right: 35,
    width: 1,
    height: 1,
    color: "#B65F28",
    colorDelay: 20,
    duration: 15,
    zIndex: 5,
  },
];

// export const FooterSectionSquaresConfig = [
//   {
//     x: 0,
//     y: 5,
//     width: 4,
//     height: 1,
//     color: "#F7F4F0",
//     colorDelay: 20,
//     duration: 15,
//     zIndex: 0,
//     /* moveToX 13,
//     moveToY: 2,
//     moveDuration: 6, */
//   },
//   {
//     x: 0,
//     y: 3,
//     width: 2,
//     height: 2,
//     color: "#F7F4F0",
//     colorDelay: 20,
//     duration: 15,
//     zIndex: 0,
//   },
//   {
//     x: 0,
//     y: 2,
//     width: 1,
//     height: 1,
//     color: "#F7F4F0",
//     colorDelay: 20,
//     duration: 15,
//     zIndex: 0,
//     /* moveToX 13,
//     moveToY: 2,
//     moveDuration: 6, */
//   },
//   {
//     x: 0,
//     y: 1,
//     width: 1,
//     height: 1,
//     color: "#f78035",
//     colorDelay: 20,
//     duration: 15,
//     zIndex: 0,
//     /* moveToX 13,
//     moveToY: 2,
//     moveDuration: 6, */
//   },
//   {
//     x: 2,
//     y: 2,
//     width: 1,
//     height: 1,
//     color: "#F7F4F0",
//     colorDelay: 20,
//     duration: 15,
//     zIndex: 0,
//     /* moveToX 13,
//     moveToY: 2,
//     moveDuration: 6, */
//   },
//   {
//     x: 2,
//     y: 4,
//     width: 1,
//     height: 1,
//     color: "#f78035",
//     colorDelay: 20,
//     duration: 15,
//     zIndex: 0,
//     /* moveToX 13,
//     moveToY: 2,
//     moveDuration: 6, */
//   },
//   {
//     x: 4,
//     y: 4,
//     width: 2,
//     height: 2,
//     color: "#B65F28",
//     colorDelay: 20,
//     duration: 15,
//     zIndex: 0,
//     /* moveToX 13,
//     moveToY: 2,
//     moveDuration: 6, */
//   },
//   {
//     x: 6,
//     y: 5,
//     width: 1,
//     height: 1,
//     color: "#F7F4F0",
//     colorDelay: 20,
//     duration: 15,
//     zIndex: 0,
//     /* moveToX 13,
//     moveToY: 2,
//     moveDuration: 6, */
//   },
//   // f78035   B65F28
//   {
//     x: 6,
//     y: 5,
//     width: 1,
//     height: 1,
//     color: "#F7F4F0",
//     colorDelay: 20,
//     duration: 15,
//     zIndex: 0,
//     /* moveToX 13,
//     moveToY: 2,
//     moveDuration: 6, */
//   },
//   //////////////////////////////

//   {
//     x: 20,
//     y: 2,
//     width: 4,
//     height: 4,
//     color: "#F7F4F0",
//     colorDelay: 20,
//     duration: 15,
//     zIndex: 0,
//   },
//   {
//     x: 17,
//     y: 5,
//     width: 3,
//     height: 1,
//     color: "#F7F4F0",
//     colorDelay: 20,
//     duration: 15,
//     zIndex: 1,
//   },
//   {
//     x: 16,
//     y: 5,
//     width: 1,
//     height: 1,
//     color: "#f78035",
//     colorDelay: 20,
//     duration: 15,
//     zIndex: 0,
//   },
//   {
//     x: 19,
//     y: 4,
//     width: 1,
//     height: 1,
//     color: "#f78035",
//     colorDelay: 20,
//     duration: 15,
//     zIndex: 0,
//   },
//   {
//     x: 20,
//     y: 3,
//     width: 1,
//     height: 1,
//     color: "#f78035",
//     colorDelay: 20,
//     duration: 15,
//     zIndex: 0,
//   },
//   {
//     x: 21,
//     y: 2,
//     width: 1,
//     height: 1,
//     color: "#f78035",
//     colorDelay: 20,
//     duration: 15,
//     zIndex: 2,
//   },
//   {
//     x: 20,
//     y: 3,
//     width: 1,
//     height: 1,
//     color: "#F7F4F0",
//     colorDelay: 20,
//     duration: 15,
//     zIndex: 2,
//   },
//   {
//     x: 20,
//     y: 2,
//     width: 2,
//     height: 2,
//     color: "#111111",
//     colorDelay: 20,
//     duration: 15,
//     zIndex: 1,
//   },
//   {
//     x: 23,
//     y: 1,
//     width: 1,
//     height: 1,
//     color: "#F7F4F0",
//     colorDelay: 20,
//     duration: 15,
//     zIndex: 3,
//   },
// ];

export const FooterLeftRightSquares = [
  /* LEFT ONE */
  {
    bottom: 0,
    left: 0,
    width: 4,
    height: 1,
    color: "#F7F4F0",
    colorDelay: 20,
    duration: 15,
    zIndex: 0,
  },

  {
    bottom: 1,
    left: 2,
    width: 1,
    height: 1,
    color: "#f78035",
    colorDelay: 20,
    duration: 15,
    zIndex: 0,
  },
  {
    bottom: 0,
    left: 4,
    width: 2,
    height: 2,
    color: "#B65F28",
    colorDelay: 20,
    duration: 15,
    zIndex: 0,
  },

  {
    bottom: 1,
    left: 0,
    width: 2,
    height: 2,
    color: "#F7F4F0",
    colorDelay: 20,
    duration: 15,
    zIndex: 0,
  },
  {
    bottom: 3,
    left: 0,
    width: 1,
    height: 1,
    color: "#F7F4F0",
    colorDelay: 20,
    duration: 15,
    zIndex: 0,
  },
  {
    bottom: 5,
    left: 0,
    width: 1,
    height: 1,
    color: "#f78035",
    colorDelay: 20,
    duration: 15,
    zIndex: 0,
  },

  {
    bottom: 4,
    left: 0,
    width: 1,
    height: 1,
    color: "#111111",
    colorDelay: 20,
    duration: 15,
    zIndex: 0,
  },
  {
    bottom: 0,
    left: 6,
    width: 1,
    height: 1,
    color: "#f78035",
    colorDelay: 20,
    duration: 15,
    zIndex: 3,
  },

  /* right one */

  {
    bottom: 0,
    right: 0,
    width: 4,
    height: 1,
    color: "#F7F4F0",
    colorDelay: 20,
    duration: 15,
    zIndex: 0,
  },

  {
    bottom: 1,
    right: 2,
    width: 1,
    height: 1,
    color: "#f78035",
    colorDelay: 20,
    duration: 15,
    zIndex: 0,
  },
  {
    bottom: 0,
    right: 4,
    width: 2,
    height: 2,
    color: "#B65F28",
    colorDelay: 20,
    duration: 15,
    zIndex: 0,
  },

  {
    bottom: 1,
    right: 0,
    width: 2,
    height: 2,
    color: "#F7F4F0",
    colorDelay: 20,
    duration: 15,
    zIndex: 0,
  },
  {
    bottom: 3,
    right: 0,
    width: 1,
    height: 1,
    color: "#F7F4F0",
    colorDelay: 20,
    duration: 15,
    zIndex: 0,
  },
  {
    bottom: 5,
    right: 0,
    width: 1,
    height: 1,
    color: "#f78035",
    colorDelay: 20,
    duration: 15,
    zIndex: 0,
  },

  {
    bottom: 4,
    right: 0,
    width: 1,
    height: 1,
    color: "#111111",
    colorDelay: 20,
    duration: 15,
    zIndex: 0,
  },
  {
    bottom: 0,
    right: 6,
    width: 1,
    height: 1,
    color: "#f78035",
    colorDelay: 20,
    duration: 15,
    zIndex: 6,
  },
];
